- name: Base system setup
  hosts: homelab
  become: true

  tasks:
    - name: Update APT cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install base packages
      apt:
        name:
          - curl
          - vim
          - htop
          - git
          - net-tools
          - docker.io
          - docker-compose
          - ufw
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        name: OpenSSH

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

